title: CS Conference Calendar
description: A selection of Computer Science conferences.

author:
  name: Stefan Marr

twitter_username: smarr
github_username:  smarr

theme: jekyll-theme-slate

safe: false

baseurl: "/conf-deadlines" # the subpath of your site, e.g. /blog
url: "https://smarr.github.io" # the base hostname & protocol for your site


keep_files: ["deadlines.json"]

exclude:
  - Makefile
  - LICENSE
  - Gemfile
  - Gemfile.lock

deadlines:
  data_file: docs/deadlines.json
  events:
    AGERE:
      # series: https://conf.researchr.org/series/AGERE
      url: https://2019.splashcon.org/home/agere-2019
      rank:   B
      Paper:        2019-08-02
      # Notification: 2019-11-19
      # Camera Ready: 2020-01-02
      rank:   D
    ICOOOLPS:
      series: https://conf.researchr.org/series/ICOOOLPS
      rank:   D
    MoreVMs:
      series: https://2019.programming-conference.org/series/MoreVMs
      rank:   D
    Meta:
      series: https://conf.researchr.org/series/META
      rank:   D
    DLS:
      series: https://conf.researchr.org/series/DLS
      rank:   B
    POPL:
      call:   https://popl19.sigplan.org/track/POPL-2019-Research-Papers
      rank:   A

    PPoPP:
      # series: https://conf.researchr.org/series/PPoPP
      url: https://ppopp20.sigplan.org/track/PPoPP-2020-papers#Call-for-Papers
      rank:   B
      Paper:        2019-07-31
      Notification: 2019-11-19
      Camera Ready: 2020-01-02

    VMIL:
      series: https://conf.researchr.org/series/VMIL
      rank:   D

    PLDI:
      # series: https://conf.researchr.org/series/pldi
      call: https://pldi19.sigplan.org/track/pldi-2019-papers
      rank:   A

    VEE:
      series: https://conf.researchr.org/series/VEE
      rank:   B

    ECOOP:
      call:  https://2019.ecoop.org/track/ecoop-2019-papers
      rank:  A

    "OOPSLA'18":
       call: https://2018.splashcon.org/track/splash-2018-oopsla
       rank: A

    "OOPSLA'19":
       call: https://2019.splashcon.org/track/splash-2019-oopsla
       rank: A

    "<Programming> Issue 1":
        # call: https://2019.programming-conference.org/track/programming-2019-papers
        url: https://2019.programming-conference.org/track/programming-2019-papers
        rank: B
        Paper:        2020-02-01
        Notification: 2020-04-01
        Camera Ready: 2020-05-15
        Event:        2021-04-01


    "<Programming> Issue 2":
        # call: https://2019.programming-conference.org/track/programming-2019-papers
        url: https://2019.programming-conference.org/track/programming-2019-papers
        rank: B
        Paper:        2020-06-01
        Notification: 2020-08-01
        Camera Ready: 2020-09-15
        Event:        2021-04-01

    "<Programming> Issue 3":
        # call: https://2019.programming-conference.org/track/programming-2019-papers
        url: https://2019.programming-conference.org/track/programming-2019-papers
        rank: B
        Paper:        2019-10-01
        Notification: 2019-12-01
        Camera Ready: 2019-01-15
        Event:        2020-04-01

    ICSE:
        call: https://2019.icse-conferences.org/track/icse-2019-Technical-Papers
        rank: A

    ICFP:
        call: https://icfp19.sigplan.org/track/icfp-2019-papers
        rank: A

    "Onward!'18":
      call: https://2018.onward-conference.org/track/onward-2018-papers
      rank: B
    "Onward!'19":
      call: https://2019.onward-conference.org/track/onward-2019-papers
      rank: B

    MPLR:
      url: https://conf.researchr.org/home/mplr-2019
      rank: B

    EuroSys:
      url: https://www.eurosys2019.org/
      rank: A
      Abstract:     2018-09-24
      Paper:        2018-10-01
      Notification: 2018-11-21
      Event:        2019-03-25

    ASPLOS:
      url: https://asplos-conference.org/
      rank: A
      Abstract:     2018-07-31
      Paper:        2018-08-07
      Notification: 2018-11-07
      Camera Ready: 2019-01-14
      Event:        2019-04-13

    CGO:
      url: http://cgo.org/cgo2019/
      rank: B
      Abstract:     2018-08-31
      Paper:        2018-09-07
      Notification: 2018-10-30
      Event:        2019-02-16

    CC:
      url: https://cc-conference.github.io/18/
      rank:   B
      Abstract:     2018-11-03
      Paper:        2018-11-07
      Notification: 2019-01-01
      Camera Ready: 2019-01-15
      Event:        2019-02-16
