title: CS Conference Calendar
description: A selection of Computer Science conferences.

author:
  name: Stefan Marr

twitter_username: smarr
github_username:  smarr

theme: jekyll-theme-slate

safe: false

baseurl: "/conf-deadlines" # the subpath of your site, e.g. /blog
url: "https://smarr.github.io" # the base hostname & protocol for your site


keep_files: ["deadlines.json"]

exclude:
  - Makefile
  - LICENSE
  - Gemfile
  - Gemfile.lock

deadlines:
  data_file: docs/deadlines.json
  events:
    AGERE:
      series: https://conf.researchr.org/series/AGERE
      rank:   D
    ICOOOLPS:
      series: https://conf.researchr.org/series/ICOOOLPS
      rank:   D
    MoreVMs:
      series: https://2021.programming-conference.org/series/MoreVMs
      rank:   D
    Meta:
      series: https://conf.researchr.org/series/META
      rank:   D
    DLS:
      series: https://conf.researchr.org/series/DLS
      rank:   B
    POPL:
      call:   https://popl22.sigplan.org/track/POPL-2022-popl-research-papers
      rank:   A

    PPoPP:
      # series: https://conf.researchr.org/series/PPoPP
      call: https://ppopp22.sigplan.org/track/PPoPP-2022-main-conference
      rank:   B

    VMIL:
      series: https://conf.researchr.org/series/VMIL
      rank:   D

    "PLDI'22":
      # series: https://conf.researchr.org/series/pldi
      call: https://pldi22.sigplan.org/track/pldi-2022-pldi
      rank:   A

    VEE:
      series: https://conf.researchr.org/series/VEE
      rank:   B

    "ECOOP'22":
      call:  https://2022.ecoop.org/track/ecoop-2022-papers
      rank:  A

    "OOPSLA'22":
       call: https://2022.splashcon.org/track/splash-2022-oopsla
       rank: A

    "<Programming> Issue 1":
        # call: https://2019.programming-conference.org/track/programming-2019-papers
        url: https://programming-journal.org/timeline/
        rank: B
        Paper:        2022-02-01
        Notification: 2022-04-01
        Camera Ready: 2022-05-15
        Event:        2023-04-01


    "<Programming> Issue 2":
        # call: https://2019.programming-conference.org/track/programming-2019-papers
        url: https://programming-journal.org/timeline/
        rank: B
        Paper:        2022-06-01
        Notification: 2022-08-01
        Camera Ready: 2022-09-15
        Event:        2023-04-01

    "<Programming> Issue 3":
        # call: https://2019.programming-conference.org/track/programming-2019-papers
        url: https://programming-journal.org/timeline/
        rank: B
        Paper:        2022-10-01
        Notification: 2022-12-01
        Camera Ready: 2023-01-15
        Event:        2023-04-01

    "ICSE'22":
        call: https://conf.researchr.org/track/icse-2022/icse-2022-papers
        rank: A

    "ICFP'22":
        call: https://icfp22.sigplan.org/track/icfp-2022-papers
        rank: A


    "Onward!'22":
      call: https://2022.splashcon.org/track/splash-2022-Onward-papers
      rank: B

    MPLR:
      url: https://soft.vub.ac.be/mplr22/
      rank: B
      Paper:        2022-08-12
      Notification: 2022-09-14
      Camera Ready: 2022-10-05
      Event:        2022-11-04

    EuroSys:
      url: https://2022.eurosys.org/
      rank: A
      Abstract:     2021-10-01
      Paper:        2021-10-09
      Notification: 2022-01-20
      Event:        2022-04-05

    ASPLOS:
      url: https://asplos-conference.org/
      rank: A
      Paper:        2021-08-13
      Notification: 2021-11-15
      Camera Ready: 2022-01-17
      Event:        2022-02-28

    CGO:
      call: https://conf.researchr.org/track/cgo-2022/cgo-2022-main-conference
      rank: B

    CC:
      call: https://conf.researchr.org/track/CC-2022/CC-2022-research-papers
      rank:   B
